// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: hospital.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hospital message
type Hospital struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Rooms         []*Room                `protobuf:"bytes,7,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hospital) Reset() {
	*x = Hospital{}
	mi := &file_hospital_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hospital) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hospital) ProtoMessage() {}

func (x *Hospital) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hospital.ProtoReflect.Descriptor instead.
func (*Hospital) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{0}
}

func (x *Hospital) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hospital) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hospital) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Hospital) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Hospital) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Hospital) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Hospital) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// Room message
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HospitalId    uint64                 `protobuf:"varint,3,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_hospital_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetHospitalId() uint64 {
	if x != nil {
		return x.HospitalId
	}
	return 0
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request messages
type CreateHospitalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Rooms         []string               `protobuf:"bytes,4,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHospitalRequest) Reset() {
	*x = CreateHospitalRequest{}
	mi := &file_hospital_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHospitalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHospitalRequest) ProtoMessage() {}

func (x *CreateHospitalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHospitalRequest.ProtoReflect.Descriptor instead.
func (*CreateHospitalRequest) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHospitalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHospitalRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateHospitalRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateHospitalRequest) GetRooms() []string {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type GetHospitalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHospitalRequest) Reset() {
	*x = GetHospitalRequest{}
	mi := &file_hospital_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHospitalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHospitalRequest) ProtoMessage() {}

func (x *GetHospitalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHospitalRequest.ProtoReflect.Descriptor instead.
func (*GetHospitalRequest) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{3}
}

func (x *GetHospitalRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateHospitalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Rooms         []string               `protobuf:"bytes,5,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHospitalRequest) Reset() {
	*x = UpdateHospitalRequest{}
	mi := &file_hospital_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHospitalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHospitalRequest) ProtoMessage() {}

func (x *UpdateHospitalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHospitalRequest.ProtoReflect.Descriptor instead.
func (*UpdateHospitalRequest) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateHospitalRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateHospitalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateHospitalRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateHospitalRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateHospitalRequest) GetRooms() []string {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type DeleteHospitalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHospitalRequest) Reset() {
	*x = DeleteHospitalRequest{}
	mi := &file_hospital_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHospitalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHospitalRequest) ProtoMessage() {}

func (x *DeleteHospitalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHospitalRequest.ProtoReflect.Descriptor instead.
func (*DeleteHospitalRequest) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteHospitalRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListHospitalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHospitalsRequest) Reset() {
	*x = ListHospitalsRequest{}
	mi := &file_hospital_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHospitalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHospitalsRequest) ProtoMessage() {}

func (x *ListHospitalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHospitalsRequest.ProtoReflect.Descriptor instead.
func (*ListHospitalsRequest) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{6}
}

func (x *ListHospitalsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListHospitalsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HospitalId    uint64                 `protobuf:"varint,1,opt,name=hospital_id,json=hospitalId,proto3" json:"hospital_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsRequest) Reset() {
	*x = GetRoomsRequest{}
	mi := &file_hospital_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsRequest) ProtoMessage() {}

func (x *GetRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomsRequest) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomsRequest) GetHospitalId() uint64 {
	if x != nil {
		return x.HospitalId
	}
	return 0
}

// Response messages
type DeleteHospitalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHospitalResponse) Reset() {
	*x = DeleteHospitalResponse{}
	mi := &file_hospital_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHospitalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHospitalResponse) ProtoMessage() {}

func (x *DeleteHospitalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHospitalResponse.ProtoReflect.Descriptor instead.
func (*DeleteHospitalResponse) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteHospitalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListHospitalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hospitals     []*Hospital            `protobuf:"bytes,1,rep,name=hospitals,proto3" json:"hospitals,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHospitalsResponse) Reset() {
	*x = ListHospitalsResponse{}
	mi := &file_hospital_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHospitalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHospitalsResponse) ProtoMessage() {}

func (x *ListHospitalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHospitalsResponse.ProtoReflect.Descriptor instead.
func (*ListHospitalsResponse) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{9}
}

func (x *ListHospitalsResponse) GetHospitals() []*Hospital {
	if x != nil {
		return x.Hospitals
	}
	return nil
}

func (x *ListHospitalsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsResponse) Reset() {
	*x = GetRoomsResponse{}
	mi := &file_hospital_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsResponse) ProtoMessage() {}

func (x *GetRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsResponse) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{10}
}

func (x *GetRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_hospital_proto protoreflect.FileDescriptor

const file_hospital_proto_rawDesc = "" +
	"\n" +
	"\x0ehospital.proto\x12\bhospital\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x01\n" +
	"\bHospital\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12$\n" +
	"\x05rooms\x18\a \x03(\v2\x0e.hospital.RoomR\x05rooms\"\xc1\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vhospital_id\x18\x03 \x01(\x04R\n" +
	"hospitalId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"q\n" +
	"\x15CreateHospitalRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05rooms\x18\x04 \x03(\tR\x05rooms\"$\n" +
	"\x12GetHospitalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x81\x01\n" +
	"\x15UpdateHospitalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x14\n" +
	"\x05rooms\x18\x05 \x03(\tR\x05rooms\"'\n" +
	"\x15DeleteHospitalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"D\n" +
	"\x14ListHospitalsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"2\n" +
	"\x0fGetRoomsRequest\x12\x1f\n" +
	"\vhospital_id\x18\x01 \x01(\x04R\n" +
	"hospitalId\"2\n" +
	"\x16DeleteHospitalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\x15ListHospitalsResponse\x120\n" +
	"\thospitals\x18\x01 \x03(\v2\x12.hospital.HospitalR\thospitals\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"8\n" +
	"\x10GetRoomsResponse\x12$\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0e.hospital.RoomR\x05rooms2\xd6\x03\n" +
	"\x0fHospitalService\x12G\n" +
	"\x0eCreateHospital\x12\x1f.hospital.CreateHospitalRequest\x1a\x12.hospital.Hospital\"\x00\x12A\n" +
	"\vGetHospital\x12\x1c.hospital.GetHospitalRequest\x1a\x12.hospital.Hospital\"\x00\x12G\n" +
	"\x0eUpdateHospital\x12\x1f.hospital.UpdateHospitalRequest\x1a\x12.hospital.Hospital\"\x00\x12U\n" +
	"\x0eDeleteHospital\x12\x1f.hospital.DeleteHospitalRequest\x1a .hospital.DeleteHospitalResponse\"\x00\x12R\n" +
	"\rListHospitals\x12\x1e.hospital.ListHospitalsRequest\x1a\x1f.hospital.ListHospitalsResponse\"\x00\x12C\n" +
	"\bGetRooms\x12\x19.hospital.GetRoomsRequest\x1a\x1a.hospital.GetRoomsResponse\"\x00B5Z3github.com/sergeimurashev/hospital-system-api/protob\x06proto3"

var (
	file_hospital_proto_rawDescOnce sync.Once
	file_hospital_proto_rawDescData []byte
)

func file_hospital_proto_rawDescGZIP() []byte {
	file_hospital_proto_rawDescOnce.Do(func() {
		file_hospital_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hospital_proto_rawDesc), len(file_hospital_proto_rawDesc)))
	})
	return file_hospital_proto_rawDescData
}

var file_hospital_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_hospital_proto_goTypes = []any{
	(*Hospital)(nil),               // 0: hospital.Hospital
	(*Room)(nil),                   // 1: hospital.Room
	(*CreateHospitalRequest)(nil),  // 2: hospital.CreateHospitalRequest
	(*GetHospitalRequest)(nil),     // 3: hospital.GetHospitalRequest
	(*UpdateHospitalRequest)(nil),  // 4: hospital.UpdateHospitalRequest
	(*DeleteHospitalRequest)(nil),  // 5: hospital.DeleteHospitalRequest
	(*ListHospitalsRequest)(nil),   // 6: hospital.ListHospitalsRequest
	(*GetRoomsRequest)(nil),        // 7: hospital.GetRoomsRequest
	(*DeleteHospitalResponse)(nil), // 8: hospital.DeleteHospitalResponse
	(*ListHospitalsResponse)(nil),  // 9: hospital.ListHospitalsResponse
	(*GetRoomsResponse)(nil),       // 10: hospital.GetRoomsResponse
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
}
var file_hospital_proto_depIdxs = []int32{
	11, // 0: hospital.Hospital.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: hospital.Hospital.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: hospital.Hospital.rooms:type_name -> hospital.Room
	11, // 3: hospital.Room.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: hospital.Room.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: hospital.ListHospitalsResponse.hospitals:type_name -> hospital.Hospital
	1,  // 6: hospital.GetRoomsResponse.rooms:type_name -> hospital.Room
	2,  // 7: hospital.HospitalService.CreateHospital:input_type -> hospital.CreateHospitalRequest
	3,  // 8: hospital.HospitalService.GetHospital:input_type -> hospital.GetHospitalRequest
	4,  // 9: hospital.HospitalService.UpdateHospital:input_type -> hospital.UpdateHospitalRequest
	5,  // 10: hospital.HospitalService.DeleteHospital:input_type -> hospital.DeleteHospitalRequest
	6,  // 11: hospital.HospitalService.ListHospitals:input_type -> hospital.ListHospitalsRequest
	7,  // 12: hospital.HospitalService.GetRooms:input_type -> hospital.GetRoomsRequest
	0,  // 13: hospital.HospitalService.CreateHospital:output_type -> hospital.Hospital
	0,  // 14: hospital.HospitalService.GetHospital:output_type -> hospital.Hospital
	0,  // 15: hospital.HospitalService.UpdateHospital:output_type -> hospital.Hospital
	8,  // 16: hospital.HospitalService.DeleteHospital:output_type -> hospital.DeleteHospitalResponse
	9,  // 17: hospital.HospitalService.ListHospitals:output_type -> hospital.ListHospitalsResponse
	10, // 18: hospital.HospitalService.GetRooms:output_type -> hospital.GetRoomsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_hospital_proto_init() }
func file_hospital_proto_init() {
	if File_hospital_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hospital_proto_rawDesc), len(file_hospital_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hospital_proto_goTypes,
		DependencyIndexes: file_hospital_proto_depIdxs,
		MessageInfos:      file_hospital_proto_msgTypes,
	}.Build()
	File_hospital_proto = out.File
	file_hospital_proto_goTypes = nil
	file_hospital_proto_depIdxs = nil
}
